#!/usr/bin/env node
// Copyright 2026 Glorktelligence — Harry Smith
// Licensed under the Apache License, Version 2.0
// See LICENSE file for full terms

/**
 * Syncs the version from the root VERSION file to all package.json files
 * and the protocol version constant. Single source of truth.
 *
 * Usage: node scripts/sync-version.mjs
 * Or:    pnpm run version:sync
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');

const version = readFileSync(join(ROOT, 'VERSION'), 'utf-8').trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`Invalid version in VERSION file: "${version}"`);
  process.exit(1);
}

console.log(`Syncing version: ${version}`);
let count = 0;

// ---------------------------------------------------------------------------
// Root package.json
// ---------------------------------------------------------------------------

function syncPackageJson(pkgPath, label) {
  try {
    const raw = readFileSync(pkgPath, 'utf-8');
    const pkg = JSON.parse(raw);
    if (pkg.version === version) {
      console.log(`  = ${label} (already ${version})`);
    } else {
      const old = pkg.version;
      pkg.version = version;
      writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
      console.log(`  \u2713 ${label} (${old} \u2192 ${version})`);
    }
    count++;
  } catch {
    // skip if no package.json
  }
}

syncPackageJson(join(ROOT, 'package.json'), 'package.json');

// ---------------------------------------------------------------------------
// All packages/*/package.json
// ---------------------------------------------------------------------------

for (const dir of readdirSync(join(ROOT, 'packages'), { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const pkgPath = join(ROOT, 'packages', dir.name, 'package.json');
  syncPackageJson(pkgPath, `packages/${dir.name}/package.json`);
}

// ---------------------------------------------------------------------------
// Protocol version constant — rewrite constants/version.ts
// ---------------------------------------------------------------------------

const versionTsPath = join(ROOT, 'packages', 'protocol', 'src', 'constants', 'version.ts');
const versionTs = `// Auto-generated by scripts/sync-version.mjs — do not edit manually
// Copyright 2026 Glorktelligence — Harry Smith
// Licensed under the Apache License, Version 2.0
// See LICENSE file for full terms

/** Current protocol version. Synced from root VERSION file. */
export const PROTOCOL_VERSION = '${version}' as const;
`;
const existingContent = (() => {
  try { return readFileSync(versionTsPath, 'utf-8'); } catch { return ''; }
})();
if (existingContent.includes(`'${version}'`)) {
  console.log(`  = packages/protocol/src/constants/version.ts (already ${version})`);
} else {
  writeFileSync(versionTsPath, versionTs);
  console.log(`  \u2713 packages/protocol/src/constants/version.ts`);
}
count++;

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

console.log(`\n\u2705 ${count} files synced to v${version}`);
