// Copyright 2026 Glorktelligence — Harry Smith
// Licensed under the Apache License, Version 2.0
// See LICENSE file for full terms

/**
 * Protocol error codes following the format BASTION-CXXX.
 * Categories: 1XXX=Connection, 2XXX=Auth, 3XXX=Protocol,
 * 4XXX=Safety, 5XXX=File, 6XXX=Provider, 7XXX=Config, 8XXX=Budget
 */
export const ERROR_CODES = {
  // --- 1XXX: Connection Errors ---
  CONNECTION_REFUSED: 'BASTION-1001',
  TLS_HANDSHAKE_FAILED: 'BASTION-1002',
  MALICLAW_REJECTED: 'BASTION-1003',
  SESSION_CONFLICT: 'BASTION-1004',
  SESSION_SUPERSEDED: 'BASTION-1005',
  SESSION_EXPIRED: 'BASTION-1006',
  HEARTBEAT_TIMEOUT: 'BASTION-1007',

  // --- 2XXX: Authentication Errors ---
  AUTH_INVALID_CREDENTIALS: 'BASTION-2001',
  AUTH_JWT_EXPIRED: 'BASTION-2002',
  AUTH_JWT_INVALID: 'BASTION-2003',
  AUTH_PROVIDER_NOT_APPROVED: 'BASTION-2004',
  AUTH_RATE_LIMITED: 'BASTION-2005',
  AUTH_ADMIN_LOCKOUT: 'BASTION-2006',

  // --- 3XXX: Protocol Errors ---
  SCHEMA_VALIDATION_FAILED: 'BASTION-3001',
  UNKNOWN_MESSAGE_TYPE: 'BASTION-3002',
  INVALID_CORRELATION_ID: 'BASTION-3003',
  MESSAGE_TOO_LARGE: 'BASTION-3004',
  PROTOCOL_VERSION_MISMATCH: 'BASTION-3005',
  RATE_LIMIT_EXCEEDED: 'BASTION-3006',

  // --- 4XXX: Safety Errors ---
  SAFETY_DENIAL_LAYER1: 'BASTION-4001',
  SAFETY_CHALLENGE_LAYER2: 'BASTION-4002',
  SAFETY_CLARIFICATION_LAYER3: 'BASTION-4003',
  SAFETY_FLOOR_VIOLATION: 'BASTION-4004',
  SAFETY_BUDGET_EXHAUSTED: 'BASTION-4005',
  SAFETY_TIME_RESTRICTION: 'BASTION-4006',

  // --- 5XXX: File Transfer Errors ---
  FILE_HASH_MISMATCH: 'BASTION-5001',
  FILE_TOO_LARGE: 'BASTION-5002',
  FILE_TYPE_BLOCKED: 'BASTION-5003',
  FILE_QUARANTINE_FULL: 'BASTION-5004',
  FILE_TRANSFER_REJECTED: 'BASTION-5005',
  FILE_PURGE_FAILED: 'BASTION-5006',
  FILE_DECRYPTION_FAILED: 'BASTION-5007',

  // --- 6XXX: Provider Errors ---
  PROVIDER_UNAVAILABLE: 'BASTION-6001',
  PROVIDER_AUTH_FAILED: 'BASTION-6002',
  PROVIDER_RATE_LIMITED: 'BASTION-6003',
  PROVIDER_QUOTA_EXCEEDED: 'BASTION-6004',
  PROVIDER_TIMEOUT: 'BASTION-6005',
  PROVIDER_ERROR: 'BASTION-6006',

  // --- 7XXX: Configuration Errors ---
  CONFIG_INVALID: 'BASTION-7001',
  CONFIG_FLOOR_VIOLATION: 'BASTION-7002',
  CONFIG_KEY_ROTATION_FAILED: 'BASTION-7003',
  CONFIG_ADMIN_KEY_INVALID: 'BASTION-7004',
  CONFIG_REGISTRY_MODIFICATION_DENIED: 'BASTION-7005',

  // --- 8XXX: Budget Errors ---
  BUDGET_MONTHLY_EXHAUSTED: 'BASTION-8001',
  BUDGET_DAILY_EXHAUSTED: 'BASTION-8002',
  BUDGET_SESSION_EXHAUSTED: 'BASTION-8003',
  BUDGET_CONFIG_COOLDOWN: 'BASTION-8004',
  BUDGET_CONFIG_CHALLENGE_HOURS: 'BASTION-8005',
} as const;

/** Union type of all error code strings. */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
