// Auto-generated by scripts/sync-version.mjs — do not edit manually
// Copyright 2026 Glorktelligence — Harry Smith
// Licensed under the Apache License, Version 2.0
// See LICENSE file for full terms

/** Current protocol version. Synced from root VERSION file. */
export const PROTOCOL_VERSION = '0.8.0' as const;
